# Generated by Django 4.2.23 on 2025-09-18 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='درصد تخفیف برای مشتری', max_digits=5)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='درصد کمیسیون برای بازاریاب', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='حداکثر تعداد استفاده (خالی = نامحدود)', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(limit_choices_to={'user_type': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ تخفیف', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ اصلی قبل از تخفیف', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_usages', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_usage', to='payments.purchase')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('referral_code', 'purchase')},
            },
        ),
        migrations.CreateModel(
            name='MarketerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('marketer', models.ForeignKey(limit_choices_to={'user_type': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('referral_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='payments.referralusage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='payments.referralcode'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='payments.referralcode'),
        ),
    ]
