# Generated by Django 4.2.23 on 2025-09-18 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_referralcode_purchase_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketerRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('experience_level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'متخصص')], max_length=20)),
                ('current_job', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_area', models.CharField(choices=[('medical', 'دوره\u200cهای پزشکی و سلامت'), ('technology', 'دوره\u200cهای تکنولوژی'), ('business', 'دوره\u200cهای کسب و کار'), ('education', 'دوره\u200cهای آموزشی'), ('all', 'همه موضوعات')], max_length=20)),
                ('motivation', models.TextField()),
                ('marketing_experience', models.TextField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت\u200cهای ادمین', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user',)},
            },
        ),
    ]
