# Generated by Django 4.2.23 on 2025-10-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_marketerregistrationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم\u200cهای سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'ثبت\u200cنام', 'verbose_name_plural': 'ثبت\u200cنام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='marketercommission',
            options={'ordering': ['-created_at'], 'verbose_name': 'کمیسیون بازاریاب', 'verbose_name_plural': 'کمیسیون\u200cهای بازاریاب'},
        ),
        migrations.AlterModelOptions(
            name='marketerregistrationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست عضویت بازاریاب', 'verbose_name_plural': 'درخواست\u200cهای عضویت بازاریاب'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'خرید', 'verbose_name_plural': 'خریدها'},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'کد معرف', 'verbose_name_plural': 'کدهای معرف'},
        ),
        migrations.AlterModelOptions(
            name='referralusage',
            options={'ordering': ['-created_at'], 'verbose_name': 'استفاده از کد معرف', 'verbose_name_plural': 'استفاده\u200cهای کد معرف'},
        ),
        migrations.AlterModelOptions(
            name='videoprogress',
            options={'verbose_name': 'پیشرفت ویدیو', 'verbose_name_plural': 'پیشرفت ویدیوها'},
        ),
    ]
