# Generated by Django 4.2.23 on 2025-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_discount_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='درصد تخفیف پیش\u200cفرض برای کدهای معرفی جدید', max_digits=5)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='درصد کمیسیون پیش\u200cفرض برای کدهای معرفی جدید', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات کدهای معرفی',
                'verbose_name_plural': 'تنظیمات کدهای معرفی',
            },
        ),
    ]
