# Generated by Django 4.2.23 on 2025-10-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'پیوست', 'verbose_name_plural': 'پیوست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order'], 'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیوها'},
        ),
    ]
