# Generated by Django 4.2.23 on 2025-10-16 09:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_attachment_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.TextField(max_length=500)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='مجموع قیمت دوره\u200cها بدون تخفیف', max_digits=10)),
                ('package_price', models.DecimalField(decimal_places=2, help_text='قیمت پکیج با تخفیف', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='درصد تخفیف', max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='package_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='packages', to='courses.course')),
            ],
            options={
                'verbose_name': 'پکیج دوره',
                'verbose_name_plural': 'پکیج\u200cهای دوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
